apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: credit-scoring-hpa
  namespace: python-api-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: credit-scoring
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40 # No scale if CPU usage is < 40%
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 5
    scaleUp:
      stabilizationWindowSeconds: 5