# kubectl apply -f service.yaml
apiVersion: v1
kind: Service
metadata:
  name: credit-scoring-service
  namespace: python-api-namespace
spec:
  type: LoadBalancer
  selector:
    app: credit-scoring
  ports:
    - protocol: TCP 
      port: 8000 # Port on which the service listens in the cluster
      targetPort: 8000 # Port on which the container listens in the pod
      #nodePort: 30000 # Port on which the service listens on the nodes