name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: add a system path
        run: |
          echo "$HOME/packages/credit_scoring" >> "$GITHUB_PATH"
      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff and flake8
        run: |  
          pip install ruff==0.2.2 flake8
          ruff --output-format=github --target-version=py39 .
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        continue-on-error: true
      - name: Test with pytest
        run: |  
          pip install coverage  
          coverage run -m pytest  -v -s
      - name: Generate Coverage Report
        run: |  
          coverage report -m